# Generated by Django 4.2.17 on 2025-04-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_alter_status_options"),
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donation_status",
                to="worker.status",
            ),
        ),
    ]
