# Generated by Django 4.2.17 on 2025-05-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0002_alter_donation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
