# Generated by Django 4.2.17 on 2025-05-03 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0004_inventory_units_allocated_location_link_and_more"),
        ("donor", "0003_alter_donation_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donation_location",
                to="worker.location",
            ),
        ),
    ]
