# Generated by Django 4.2.17 on 2025-04-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Stauts", "verbose_name_plural": "Stautses"},
        ),
    ]
