# Generated by Django 4.2.17 on 2025-05-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_alter_status_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
    ]
