# Generated by Django 4.2.17 on 2025-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0003_alter_status_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="units_allocated",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="location",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("clinic", "Clinic"),
                    ("donation_centre", "Donation Centre"),
                    ("van", "Van"),
                    ("lab", "Lab"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
