# Generated by Django 4.2.17 on 2025-08-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0004_inventory_units_allocated_location_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Status", "verbose_name_plural": "Statuses"},
        ),
        migrations.AddField(
            model_name="inventory",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                default="A+",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
