# Generated by Django 4.2.17 on 2025-06-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0004_inventory_units_allocated_location_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Status", "verbose_name_plural": "Statuses"},
        ),
    ]
