# Generated by Django 4.2.17 on 2025-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0005_alter_status_options_inventory_blood_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
    ]
