# Generated by Django 4.2.17 on 2025-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="units_required",
            field=models.IntegerField(default=1),
        ),
    ]
