# Generated by Django 4.2.17 on 2025-02-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="blood_group",
        ),
    ]
